image:
  file: Dockerfile
tasks:
  - before: clear && task init
    command: clear && task serve
  - command: clear && printf "%s\n" "You can access port 3000 of this gitpod via \"$(gp url 3000)\"". && sleep 5 && task watch
    openIn: main
ports:
  - port: 3000
    