image:
  file: Dockerfile
tasks:
  - before: clear && wget https://github.com/tillhoff/serve/releases/download/v0.0.2/serve_linux_amd64 -O /dev/serve
    command: clear && task serve
  - before: clear && wget https://github.com/tillhoff/temingo/releases/download/v0.0.1/temingo_linux_amd64 -O /dev/temingo
    command: clear && printf "%s\n" "You can access port 3000 of this gitpod via \"$(gp url 3000)\"". && sleep 5 && task watch
ports:
  - port: 3000
    