image:
  file: Dockerfile
tasks:
  - before: clear && .gitpod/before.sh
  - command: clear && task serve
    openIn: main
  - command: clear && task watch
    openIn: main
  - command: clear && printf "%s\n" "You can access port 3000 of this gitpod via \"$(gp url 3000)\"".
    openIn: main
ports:
  - port: 3000
    