tasks:
  - before: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -b /usr/local/bin
  - init: |
      if [[ ! -f ../serve/serve ]]; then
        git clone https://github.com/tillhoff/serve ../serve
        cd ../serve && task build
      fi

      if [[ ! -f ../temingo/temingo ]]; then
        git clone https://github.com/tillhoff/temingo.. /temingo
        cd ../temingo && task build
      fi
  - command: task serve
    openIn: main
  - command: task watch
    openIn: main
  - command: You can access port 3000 of this gitpod via "$(gp url 3000)".
    openIn: main
ports:
  - port: 3000
    