[[headers]]
    # Define which paths this specific [[headers]] block will cover.
    for = "/*"

    [headers.values]
        # Configure feature usage.
        Feature-Policy = """
            camera none;
            geolocation none;
            gyroscope none;
            fullscreen self;
            magnetometer none;
            microphone none;
            midi none;
            notifications none;
            push none;
            speaker self;
            sync-xhr none;
            vibrate none;
        """
