# https://taskfile.dev

version: '3'

silent: true

tasks:
  build:
    desc: Build the files / templating
    cmds:
      - |
        mv ./output/static ./static_temp && \
        rm -dr ./output/* && \
        mkdir -p ./output && \
        mv ./static_temp ./output/static || true
      - |
        ../temingo/temingo{{ .EXTENSION }} \
        --valuesfile values.yaml \
        --inputDir . \
        --partialsDir partials \
        --outputDir output \
        --templateExtension .html.template \
        --partialExtension .template \
        --generatedExtension .html
    vars:
      EXTENSION: '{{ if eq OS "windows" }}.exe{{ end }}'

  serve:
    desc: Start the dev-server
    dir: output
    cmds:
      - "../../serve/serve{{ .EXTENSION }}"
    vars:
      EXTENSION: '{{ if eq OS "windows" }}.exe{{ end }}'
