title: Rahoff

css:

  generalsize: 1rem # size of elements
  fontsize: 1rem
  containerwidth: 1150px # defines the max-width of containers

  colors:
    primaryColor:
      hue: 0
      saturation: 100%
      lightness: 43%
      alpha: 1
    
    primaryBgColor:
      hue: 0
      saturation: 0%
      lightness: 60%
      alpha: 1
    
    siteColor:
      hue: 0
      saturation: 0%
      lightness: 10%
      alpha: 1
    siteBgColor:
      hue: 0
      saturation: 0%
      lightness: 90%
      alpha: 1

    buttonColor:
      hue: 0
      saturation: 0%
      lightness: 10% # equal to site color looks good
      alpha: 1
    buttonBgColor:
      hue: 0
      saturation: 0%
      lightness: 90% # equal to site bg color looks good
      alpha: 1
    
    borderColor:
      hue: 0
      saturation: 0%
      lightness: 20% # between site color & site bg color looks good
      alpha: 1

  borders:
    radius: 5px
    width: 2px

  buttons:
    padding: 0.5rem
  
  animations:
    transitionDuration: 0.2s

  navigation:
    padding: 0.5rem

factors:
  icons: 1.2
  sizes:
    #regular: 1 # just for reference - not actually used anywhere
    large: 1.2
    big: 1.4
    huge: 1.6
