baseURL: "https://rahoff.enforge.de"
languageCode: "de-de"
title: "rahoff.enforge.de"
sectionPagesMenu: "main"

menu:
  main:
    - identifier: "jewellery"
      name: "Schmuck"
      weight: 10
      url: "/jewellery/"
    - identifier: "pictures"
      name: "Bilder"
      weight: 20
      url: "/pictures/"
    - identifier: "sculptures"
      name: "Skulpturen"
      weight: 30
      url: "/sculptures/"
    - identifier: "ecar"
      name: "Elektroauto"
      weight: 100
      url: "/ecar/"

summaryLength: 20
