baseURL: "https://rahoff.enforge.de"
languageCode: "de-de"
title: "rahoff.enforge.de"
sectionPagesMenu: "main"

menu:
  main:
    - identifier: "schmuck"
      name: "Schmuck"
      weight: 10
      url: "/schmuck/"
    - identifier: "bilder"
      name: "Bilder"
      weight: 20
      url: "/bilder/"
    - identifier: "skulpturen"
      name: "Skulpturen"
      weight: 30
      url: "/skulpturen/"
    - identifier: "eauto"
      name: "Elektroauto"
      weight: 100
      url: "/eauto/"

summaryLength: 20
